//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexasHoldem.Database.BackupOldFrameworks.EntityNewTry
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public int logId { get; set; }
        public string msg { get; set; }
        public int roomId { get; set; }
        public int game_Id { get; set; }
    
        public virtual GameRoom GameRoom { get; set; }
        public virtual Log Log { get; set; }
    }
}
