//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexasHoldem.Database.mappingWntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deck
    {
        public int index { get; set; }
        public int room_Id { get; set; }
        public int game_Id { get; set; }
        public int card_value { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual GameRoom GameRoom { get; set; }
    }
}
