//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexasHoldem.Database.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public int LogPriority { get; set; }
    
        public virtual ErrorLog ErrorLog { get; set; }
        public virtual PriorityLogEnum PriorityLogEnum { get; set; }
        public virtual SystemLog SystemLog { get; set; }
    }
}
